export const demoMarketplaceProducts = [
    {
        name: "onions",
        category: "crop",
        description: "Freshly harvested red onions, rich flavor, perfect for cooking.",
        quantity: "50kg bag",
        price: 2000,
        discount_percentage: 10,
        location: "Kano, Nigeria",
        images: ["/productImages/onions.png"],
        id: 0,
        farmer_id: 0,
        is_approved: true,
        is_listed: true,
        availability: "in_stock",
        total_ratings: 23,
        average_rating: 4.5,
        created_at: "2025-09-15T21:25:49.411Z",
        updated_at: "2025-09-15T21:25:49.411Z",
        farmer: {
            id: 0,
            full_name: "John Doe",
            profile_picture: "/farmers/farmerMaleDemo.jpg",
            farm_name: "Doe Farms",
            farm_location: "Lagos, Nigeria",
            farm_type: "Vegetables",
        },
        discounted_price: 1800,
    },
    {
        name: "tomatoes",
        category: "crop",
        description: "Plump red tomatoes, perfect for sauces and salads.",
        quantity: "crate",
        price: 2500,
        discount_percentage: 5,
        location: "Ibadan, Nigeria",
        images: ["/productImages/tomatoes.png"],
        id: 1,
        farmer_id: 1,
        is_approved: true,
        is_listed: true,
        availability: "in_stock",
        total_ratings: 15,
        average_rating: 4.2,
        created_at: "2025-09-15T21:30:10.411Z",
        updated_at: "2025-09-15T21:30:10.411Z",
        farmer: {
            id: 1,
            full_name: "Mary Okoro",
            profile_picture: "/farmers/farmerMaleDemo.jpg",
            farm_name: "Okoro Greenfields",
            farm_location: "Oyo, Nigeria",
            farm_type: "Vegetables",
        },
        discounted_price: 2375,
    },
    {
        name: "yams",
        category: "crop",
        description: "Large white yams, starchy and filling, farm fresh.",
        quantity: "10 tubers",
        price: 6000,
        discount_percentage: 0,
        location: "Benue, Nigeria",
        images: ["/productImages/yams.png"],
        // images: ["../src/assets/ProductImages/yams.png"],
        id: 2,
        farmer_id: 2,
        is_approved: true,
        is_listed: true,
        availability: "in_stock",
        total_ratings: 30,
        average_rating: 4.7,
        created_at: "2025-09-15T21:35:21.411Z",
        updated_at: "2025-09-15T21:35:21.411Z",
        farmer: {
            id: 2,
            full_name: "Ahmed Musa",
            profile_picture: "/farmers/farmerFemaleDemo.jpg",
            farm_name: "Musa Agro",
            farm_location: "Makurdi, Nigeria",
            farm_type: "Roots & Tubers",
        },
        discounted_price: 6000,
    },
    {
        name: "maize",
        category: "grain",
        description: "Dried yellow maize, ready for milling or animal feed.",
        quantity: "100kg bag",
        price: 15000,
        discount_percentage: 8,
        location: "Kaduna, Nigeria",
        images: ["/productImages/maize.png"],
        id: 3,
        farmer_id: 3,
        is_approved: true,
        is_listed: true,
        availability: "in_stock",
        total_ratings: 12,
        average_rating: 4.0,
        created_at: "2025-09-15T21:40:11.411Z",
        updated_at: "2025-09-15T21:40:11.411Z",
        farmer: {
            id: 3,
            full_name: "Grace Ade",
            profile_picture: "/farmers/farmerMaleDemo.jpg",
            farm_name: "Ade Farms",
            farm_location: "Kaduna, Nigeria",
            farm_type: "Grains",
        },
        discounted_price: 13800,
    },
    {
        name: "cassava",
        category: "crop",
        description: "Fresh cassava roots, ideal for garri or fufu production.",
        quantity: "50kg bundle",
        price: 7000,
        discount_percentage: 0,
        location: "Ogun, Nigeria",
        images: ["/productImages/cassava.png"],
        id: 4,
        farmer_id: 4,
        is_approved: true,
        is_listed: true,
        availability: "in_stock",
        total_ratings: 8,
        average_rating: 3.9,
        created_at: "2025-09-15T21:45:59.411Z",
        updated_at: "2025-09-15T21:45:59.411Z",
        farmer: {
            id: 4,
            full_name: "Emeka Nwosu",
            profile_picture: "/farmers/farmerFemaleDemo.jpg",
            farm_name: "Nwosu Harvest",
            farm_location: "Abeokuta, Nigeria",
            farm_type: "Roots",
        },
        discounted_price: 7000,
    },
    {
        name: "pepper",
        category: "crop",
        description: "Spicy red peppers with strong aroma and taste.",
        quantity: "basket",
        price: 3500,
        discount_percentage: 15,
        location: "Kano, Nigeria",
        images: ["/productImages/pepper.png"],
        id: 5,
        farmer_id: 5,
        is_approved: true,
        is_listed: true,
        availability: "in_stock",
        total_ratings: 19,
        average_rating: 4.3,
        created_at: "2025-09-15T21:50:14.411Z",
        updated_at: "2025-09-15T21:50:14.411Z",
        farmer: {
            id: 5,
            full_name: "Fatima Bello",
            profile_picture: "/farmers/farmerMaleDemo.jpg",
            farm_name: "Bello Spices",
            farm_location: "Kano, Nigeria",
            farm_type: "Vegetables",
        },
        discounted_price: 2975,
    },
    {
        name: "plantain",
        category: "fruit",
        description: "Ripe yellow plantains, sweet and perfect for frying.",
        quantity: "20 bunches",
        price: 8000,
        discount_percentage: 0,
        location: "Delta, Nigeria",
        images: ["/productImages/plantain.png"],
        id: 6,
        farmer_id: 6,
        is_approved: true,
        is_listed: true,
        availability: "in_stock",
        total_ratings: 14,
        average_rating: 4.6,
        created_at: "2025-09-15T21:55:25.411Z",
        updated_at: "2025-09-15T21:55:25.411Z",
        farmer: {
            id: 6,
            full_name: "Joseph Efe",
            profile_picture: "/farmers/farmerFemaleDemo.jpg",
            farm_name: "Efe Produce",
            farm_location: "Asaba, Nigeria",
            farm_type: "Fruits",
        },
        discounted_price: 8000,
    },
    {
        name: "rice",
        category: "grain",
        description: "Unpolished local rice, nutritious and chemical-free.",
        quantity: "50kg bag",
        price: 28000,
        discount_percentage: 7,
        location: "Niger, Nigeria",
        images: ["/productImages/rice.png"],
        id: 7,
        farmer_id: 7,
        is_approved: true,
        is_listed: true,
        availability: "in_stock",
        total_ratings: 42,
        average_rating: 4.8,
        created_at: "2025-09-15T22:00:49.411Z",
        updated_at: "2025-09-15T22:00:49.411Z",
        farmer: {
            id: 7,
            full_name: "Aisha Sule",
            profile_picture: "/farmers/farmerMaleDemo.jpg",
            farm_name: "Sule Rice Mills",
            farm_location: "Bida, Nigeria",
            farm_type: "Grains",
        },
        discounted_price: 26040,
    },
    {
        name: "groundnut",
        category: "legume",
        description: "Freshly roasted groundnuts, crunchy and delicious.",
        quantity: "10kg bag",
        price: 5000,
        discount_percentage: 0,
        location: "Kaduna, Nigeria",
        images: ["/productImages/groundnut.png"],
        id: 8,
        farmer_id: 8,
        is_approved: true,
        is_listed: true,
        availability: "in_stock",
        total_ratings: 17,
        average_rating: 4.1,
        created_at: "2025-09-15T22:05:37.411Z",
        updated_at: "2025-09-15T22:05:37.411Z",
        farmer: {
            id: 8,
            full_name: "Hassan Ibrahim",
            profile_picture: "/farmers/farmerFemaleDemo.jpg",
            farm_name: "Ibrahim Agro",
            farm_location: "Zaria, Nigeria",
            farm_type: "Legumes",
        },
        discounted_price: 5000,
    },
    {
        name: "cabbage",
        category: "vegetable",
        description: "Large green cabbages, crisp and fresh from the farm.",
        quantity: "10 heads",
        price: 4000,
        discount_percentage: 5,
        location: "Plateau, Nigeria",
        images: ["/productImages/cabbage.png"],
        id: 9,
        farmer_id: 9,
        is_approved: true,
        is_listed: true,
        availability: "in_stock",
        total_ratings: 10,
        average_rating: 4.0,
        created_at: "2025-09-15T22:10:59.411Z",
        updated_at: "2025-09-15T22:10:59.411Z",
        farmer: {
            id: 9,
            full_name: "Ngozi Chukwu",
            profile_picture: "/farmers/farmerMaleDemo.jpg",
            farm_name: "Chukwu Greens",
            farm_location: "Jos, Nigeria",
            farm_type: "Vegetables",
        },
        discounted_price: 3800,
    },

    {
        name: "pepper",
        category: "crop",
        description: "Green bell peppers, crunchy and fresh for cooking.",
        quantity: "basket",
        price: 3200,
        discount_percentage: 0,
        location: "Osun, Nigeria",
        images: ["/productImages/pepper.png"],
        id: 10,
        farmer_id: 10,
        is_approved: true,
        is_listed: true,
        availability: "in_stock",
        total_ratings: 9,
        average_rating: 4.1,
        created_at: "2025-09-15T22:15:40.411Z",
        updated_at: "2025-09-15T22:15:40.411Z",
        farmer: {
            id: 10,
            full_name: "Bisi Alabi",
            profile_picture: "/farmers/farmerFemaleDemo.jpg",
            farm_name: "Alabi Produce",
            farm_location: "Osogbo, Nigeria",
            farm_type: "Vegetables",
        },
        discounted_price: 3200,
    },
    {
        name: "plantain",
        category: "fruit",
        description: "Unripe green plantains, perfect for boiling and making chips.",
        quantity: "15 bunches",
        price: 7500,
        discount_percentage: 10,
        location: "Rivers, Nigeria",
        images: ["/productImages/plantain.png"],
        id: 11,
        farmer_id: 11,
        is_approved: true,
        is_listed: true,
        availability: "in_stock",
        total_ratings: 11,
        average_rating: 4.4,
        created_at: "2025-09-15T22:20:02.411Z",
        updated_at: "2025-09-15T22:20:02.411Z",
        farmer: {
            id: 11,
            full_name: "Chinedu Okafor",
            profile_picture: "/farmers/farmerMaleDemo.jpg",
            // profile_picture: "../src/assets/images/farmerMaleDemo.jpg",
            farm_name: "Okafor Farms",
            farm_location: "Port Harcourt, Nigeria",
            farm_type: "Fruits",
        },
        discounted_price: 6750,
    }

]
